# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Smart2Pay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart2Pay
  pod 'SwiftyJSON'
  pod 'Alamofire'
end

