# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Smart2Pay Example' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'Alamofire'
  pod 'SwiftyJSON'
end
