# Uncomment the next line to define a global platform for your project
#platform :ios, '8.0'

target 'Smart2Pay Example' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'Alamofire', '~> 4.9.1'
  pod 'SwiftyJSON', '~> 5.0.0'
end
